### ISSUE TITLE
utils/export.py in wrong folder and cannot access libraries

### ISSUE THREAD

**Issue by dshivashok** [gsgen3d/gsgen#13]
Hi,

While trying to convert the .pt to .ply file using the script in utils/export.py, I encountered a few import related errors. 
```
Traceback (most recent call last):
  File "/home/jovyan/gsgen/utils/export.py", line 2, in <module>
    import numpy as np
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from . import index_tricks
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/opt/conda/envs/gsgen/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 20, in <module>
    from typing import NamedTuple, Any
  File "/home/jovyan/gsgen/utils/typing.py", line 12, in <module>
    from typing import (
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (/home/jovyan/gsgen/utils/typing.py)
```

```
Traceback (most recent call last):
  File "/home/jovyan/gsgen/utils/export.py", line 6, in <module>
    from gs.gaussian_splatting import GaussianSplattingRenderer
  File "/home/jovyan/gsgen/utils/gs/gaussian_splatting.py", line 6, in <module>
    from utils.camera import PerspectiveCameras
ModuleNotFoundError: No module named 'utils'
```
Moving export.py to /gsgen and then installing the plyfile library seemed to fix this issue.

**Comment by heheyas** [comment]
Hi coolkite,

This issue can be solved by setting the `PYTHONPATH` env var:
```bash
export PYTHONPATH="."
```
or
```bash
PYTHONPATH="." python utils/export.py <your_ckpt> --type ply
```

**Comment by Taxalfer** [comment]
i still got this problem after the operation according to the requirements
![image](https://github.com/gsgen3d/gsgen/assets/87062331/b880e2ad-12ff-41b8-bb64-064cd34e1e52)

**Comment by coolkite** [comment]
Moving the export file outside the utils directory into the gsgen folder
worked for me.

**Comment by Iliceth** [comment]
I run into the first problem too, didn't forget to set the pythonpath.

```
PYTHONPATH="." python utils/export.py /mnt/c/Users/Andy
/Documents/gsgen/checkpoints/baby_dragon_with_sunglasses_and_a_red_top_hat/2023-11-05/232556/ckpts/step_14000.pt --ty
pe ply
Traceback (most recent call last):
  File "/mnt/c/Users/Andy/Documents/gsgen/utils/export.py", line 2, in <module>
    import numpy as np
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/__init__.py", line 144, in <module>
    from . import lib
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/lib/__init__.py", line 25, in <module>
    from . import index_tricks
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/lib/index_tricks.py", line 12, in <module>
    import numpy.matrixlib as matrixlib
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/matrixlib/__init__.py", line 4, in <module>
    from . import defmatrix
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/matrixlib/defmatrix.py", line 12, in <module>
    from numpy.linalg import matrix_power
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/linalg/__init__.py", line 73, in <module>
    from . import linalg
  File "/home/user/miniconda3/envs/gsgen/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 20, in <module>
    from typing import NamedTuple, Any
  File "/mnt/c/Users/Andy/Documents/gsgen/utils/typing.py", line 12, in <module>
    from typing import (
ImportError: cannot import name 'Any' from partially initialized module 'typing' (most likely due to a circular import) (/mnt/c/Users/Andy/Documents/gsgen/utils/typing.py)
```

Are there any other tips you have?

**Comment by heheyas** [comment]
Using `python -m utils.export <your_ckpt> --type <export_type>` will solve this problem.

**Comment by Iliceth** [comment]
> Using `python -m utils.export <your_ckpt> --type <export_type>` will solve this problem.

Yes, that worked for me, thanks a lot! Could you also tell me why that is, so I can learn what happened (wrongly) please?

**Comment by heheyas** [comment]
The file `typing.py` shares the same name with python built-in typing package, the `-m` flag tells python to load from the current working directory first. You can refer [official documentation](https://docs.python.org/3/using/cmdline.html#cmdoption-m) for details.

**Comment by Iliceth** [comment]
> The file `typing.py` shares the same name with python built-in typing package, the `-m` flag tells python to load from the current working directory first. You can refer [official documentation](https://docs.python.org/3/using/cmdline.html#cmdoption-m) for details.

Thanks!
