### ISSUE TITLE
About the installation of CLIP

### ISSUE THREAD

**Issue by ch1998** [gsgen3d/gsgen#26]
I successfully installed CLIP and CLIP 1.0 is also present in pip list. But when I execute the training script, I get the following error

/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) < LooseVersion("1.15"):
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/lightning_utilities/core/imports.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/pkg_resources/__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/torchmetrics/utilities/imports.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _PYTHON_LOWER_3_8 = LooseVersion(_PYTHON_VERSION) < LooseVersion("3.8")
/home/twx/anaconda3/envs/gsgen/lib/python3.9/site-packages/torchmetrics/utilities/imports.py:24: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  _PYTHON_LOWER_3_8 = LooseVersion(_PYTHON_VERSION) < LooseVersion("3.8")
Traceback (most recent call last):
  File "/media/twx/ch/code/generate/gsgen-main/main.py", line 3, in <module>
    from trainer import Trainer
  File "/media/twx/ch/code/generate/gsgen-main/trainer.py", line 43, in <module>
    from guidance import get_guidance
  File "/media/twx/ch/code/generate/gsgen-main/guidance/__init__.py", line 27, in <module>
    from .make_it_3d import MakeIt3DGuidance
  File "/media/twx/ch/code/generate/gsgen-main/guidance/make_it_3d.py", line 17, in <module>
    import clip
ModuleNotFoundError: No module named 'clip'

**Comment by ch1998** [comment]
Reinstalling CILP successfully solved the problem
